### PR TITLE
Fixed large FAQ gap

### LINKED ISSUE #287: [Bugfix] Large gap in FAQ section
There's a large gap between the ribbon title and the accordion on desktop screens

Image

### PR DESCRIPTION
**Pull request by khushikhan0**
# Fixed large FAQ gap between title and accordion on LG screens

### ▶ Changelist:
- Fixed the large gap by changing title height on desktop
- Formatted breakpoints properly

### 🧪 Testing:
- Manual

### 🎥 Screenshots & Screencasts:
image

### CODE REVIEW

File: apps/main/src/app/sponsor-us/Sections/SponsorUsStatsComp.tsx [hunk 1]
```diff
@@ -19,9 +19,16 @@ type BalloonProps = {
 export default function SponsorUsBenefitCardComp() {
   const { isMobile, isTablet, isDesktop } = useDevice();
 
+  const outerDivStyles = clsx(
+    "relative w-full overflow-hidden",
+    isDesktop && "h-[1500px] mt-[7.5vh]",
```
Comment (agonzalez22) [inline apps/main/src/app/sponsor-us/Sections/SponsorUsStatsComp.tsx]: https://github.com/user-attachments/assets/27f4e5ae-8216-49b3-b7dd-5959e9ec919b

Idk if this video explains it well but the space between the dropdown and the ribbon title aren't as consistent between screen sizes. 

I think it also looks funky cus we don't define any additional padding as the screen gets smaller (this is optional-- not rly required and might pose some issues on smaller screens)

Comment (agonzalez22) [reply apps/main/src/app/sponsor-us/Sections/SponsorUsStatsComp.tsx]: But I would maybe try to keep the desktop height units consistent and then also play around with the mt- values that you've set here. I think they look good just want to make sure this gap isn't as big as it is. Also the previous section is a problem so we will likely rewrite it.

**Review by agonzalez22 — CHANGES_REQUESTED** [review]
Few changes u did phenom <3

File: apps/main/src/app/sponsor-us/Sections/SponsorUsStatsComp.tsx (hunk 1 above)
Comment (khushikhan0) [reply apps/main/src/app/sponsor-us/Sections/SponsorUsStatsComp.tsx]: wait this isn't the file where faq is styled but i'll work on padding

Comment (khushikhan0) [reply apps/main/src/app/sponsor-us/Sections/SponsorUsStatsComp.tsx]: was resolving merge conflicts w this file before which is why it was changed hehe

Comment (khushikhan0) [reply apps/main/src/app/sponsor-us/Sections/SponsorUsStatsComp.tsx]: https://github.com/user-attachments/assets/9a319f8e-98e9-446e-811d-dc6d9a00e2dc

https://github.com/user-attachments/assets/700c0e49-60b5-4e4a-ac10-5d7d47709278

**Review by agonzalez22 — APPROVED** [review]
THIS IS PERF AMAZING
