### PR TITLE
Fixed stats cutoff issue

### LINKED ISSUE #279: [Bugfix] Investigate Sponsor Us Stats Section Cutoff
Need to figure out why the stats section gets cut off

Image

Image

### PR DESCRIPTION
**Pull request by khushikhan0**
# Fixed stats cutoff issue

### ▶ Changelist:
- Changed height of the stats section in all views

### 📝 Notes + 🚧 TODO:
- There's overflow in the SponsorTop component that might be impacting how the breakpoints appear. When I comment out this component, my breakpoints work fine
- Tablet sizes on the smaller side look a little weird, maybe we need another breakpoint for that?

### 🧪 Testing:
- Manual

### 🎥 Screenshots & Screencasts:

https://github.com/user-attachments/assets/caf83099-bf99-4805-b244-79d2e0073f0b

### CODE REVIEW

File: apps/main/src/app/sponsor-us/Sections/SponsorUsStatsComp.tsx [hunk 1]
```diff
@@ -19,9 +19,16 @@ type BalloonProps = {
 export default function SponsorUsBenefitCardComp() {
   const { isMobile, isTablet, isDesktop } = useDevice();
 
+  const outerDivStyles = clsx(
+    "relative w-full overflow-hidden",
+    isDesktop && "h-[1500px]",
```
Comment (agonzalez22) [inline apps/main/src/app/sponsor-us/Sections/SponsorUsStatsComp.tsx]: same comment here, try to keep consistency among units for the heights given that desktop screens can be huggggge

**Review by agonzalez22 — APPROVED** [review]
Image

LGTMMMM (left comment but approved)
